package types

import (
	jwt "github.com/dgrijalva/jwt-go"
)

// JWTData is a jwt response struct
// type (
// 	JWTData struct {
// 		// Standard claims are the standard jwt claims from the IETF standard
// 		// https://tools.ietf.org/html/rfc7519
// 		jwt.StandardClaims
// 		Username string `json:"username"`
// 		ID       int    `json:"id"`
// 	}
// )

type (
	JWTData struct {
		// Standard claims are the standard jwt claims from the IETF standard
		// https://tools.ietf.org/html/rfc7519
		jwt.StandardClaims
		CustomClaims map[string]interface{} `json:"custom,omitempty"`
	}
)

// Account is the account response struct
type (
	Account struct {
		Email    string  `json:"email"`
		Balance  float64 `json:"balance"`
		Currency string  `json:"currency"`
	}
)

// User is the user response struct
type (
	User struct {
		// ID field is autogenerated and auto incremented by SQL DB
		Username string `json:"username"`
		Password string `json:"password"`
	}
)

// UserPublic is the publicly safe user data
type (
	UserPublic struct {
		// ID field is autogenerated and auto incremented by SQL DB
		ID       int    `json:"id"`
		Username string `json:"username"`
	}
)

// Post is the post response struct
type (
	Post struct {
		Body string `json:"body:"`
	}
)

// Generic JSON response
type (
	Generic struct {
		Data string `json:"data"`
	}
)
